name: kometa_images
description: Utilities set

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^4.2.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  get_it: ^7.2.0
  proviso: ^1.0.5
  hovering: ^1.0.4
  logger: ^1.0.0
  hive: ^2.0.4
  path_provider: ^2.0.2
  path: ^1.8.0
  image: ^3.0.8
  fading_edge_scrollview: ^2.0.0
  url_launcher: ^5.0.15

flutter:
  uses-material-design: true